<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IND040101141" failures="2" tests="7" name="Test" time="57.293" errors="0" timestamp="2025-05-06T10:28:08 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_Account_registration" time="3.245"/>
  <testcase classname="testCases.TC002_ValidateLoggingIntoTheApplicationUsingValidCredentials" name="validLoginTest" time="2.215"/>
  <testcase classname="testCases.TC003_LoginDDT" name="validate_ddt" time="3.335"/>
  <testcase classname="testCases.TC003_LoginDDT" name="validate_ddt" time="2.556">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.validate_ddt(TC003_LoginDDT.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_ddt -->
  <testcase classname="testCases.TC003_LoginDDT" name="validate_ddt" time="2.433">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.validate_ddt(TC003_LoginDDT.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_ddt -->
  <testcase classname="testCases.TC003_LoginDDT" name="validate_ddt" time="11.827"/>
  <testcase classname="testCases.TC003_LoginDDT" name="validate_ddt" time="2.741"/>
</testsuite> <!-- Test -->
